### ISSUE TITLE
regional build error

### ISSUE THREAD

**Issue by wangzhao0217** [nptscot/npt#475] opened 2024-05-17 08:45 UTC
Hi @Robinlovelace , I hit the error for Glasgow and Strathclyde
▶ dispatched target rs_commute_ebike
✖ errored target rs_commute_ebike
✖ errored pipeline [11.324 minutes]
Warning message:
10 targets produced warnings. Run targets::tar_meta(fields = warnings, complete_only = TRUE) for the messages. 
Error encountered in region Glasgow and Strathclyde . Error details:  Error running targets::tar_make()
Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
Debugging guide: https://books.ropensci.org/targets/debugging.html
How to ask for help: https://books.ropensci.org/targets/help.html
Last error message:
    error reading from connection
Last error traceback:
    get_routes(od = od_commute_subset, plans = "ebike", purpose = "commute",...
    readRDS(savename_f)
    .handleSimpleError(function (condition)  {     state$error <- build_mess...
    h(simpleError(msg, call))
[1] "Adding Glasgow and Strathclyde to failed_regions"
> targets::tar_meta(fields = error, complete_only = TRUE)
# A tibble: 1 × 2
  name             error                        
  <chr>            <chr>                        
1 rs_commute_ebike error reading from connection

**Comment by Robinlovelace** [comment] 2024-05-17 10:11
Hi @wangzhao0217 it's due to hardisk being full an not related to the code I think so closing for now.

**Comment by Robinlovelace** [comment] 2024-05-17 21:07
Hi Zhao, no problem. I can see there is an error. However, it's unlikely to be due to code in this repo. I'll test on another machine and happy to re-open if we can reproduce with reference to a bit of code that could be causing it.

**Closed by Robinlovelace** 2024-05-17 21:07 UTC
