### ISSUE TITLE
Targets Failing on WIndows

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#53] opened 2023-02-24 12:46 UTC
```
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 59/60
  Rate limit reset at: 2023-02-24 13:44:57 UTC
```

**Comment by mem48** [comment] 2023-02-24 12:51
That was an authentication error with GitHub, fixed

**Comment by mem48** [comment] 2023-02-24 12:51
New error

```
Linking to GEOS 3.9.3, GDAL 3.5.2, PROJ 8.2.1; sf_use_s2() is TRUE
Skipping install of 'cyclestreets' from a github remote, the SHA1 (9449bec4) has not changed since last install.
  Use `force = TRUE` to force installation
• start target subpoints_origins
✖ error target subpoints_origins
• end pipeline [0.22 seconds]
Warning messages:
1: Targets and globals must have unique names. Ignoring global objects that conflict with target names: parameters. Warnings like this one are important, but if you must suppress them, you can do so with Sys.setenv(TAR_WARN = "false"). 
2: cannot open compressed file 'inputdata/oas.Rds', probable reason 'No such file or directory' 
3: 1 targets produced warnings. Run targets::tar_meta(fields = warnings, complete_only = TRUE) for the messages. 
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: cannot open the connection

```

**Comment by mem48** [comment] 2023-02-24 12:53
inputdata is missing

**Comment by Robinlovelace** [comment] 2023-02-24 14:51
> inputdata is missing

This will be fixed by putting `inputdata` and the relevant files into the root directory of npt.

**Comment by mem48** [comment] 2023-02-24 15:57
```
ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
0 routes removed
3833: deleted
Saving tmp/batch_fastest_commute_1_with_105_routes_of_105_rows.Rds to tmp
Saving tmp/od_commute_1_with_105_of_105_rows.Rds to tmp
Combining results
✖ error target r_commute
• end pipeline [50.19 seconds]
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: no applicable method for 'st_as_sf' applied to an object of class "c('dtplyr_step_group', 'dtplyr_step')"


```

**Comment by mem48** [comment] 2023-02-26 14:02
I tried a national build

```
C:\Users\earmmor\AppData\Local\Temp\Rtmp6dtZEb/test.csv.gz
Rows: 14000 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): start_id, end_id, strategy, json
dbl (3): distance, time_seconds, calories
\
ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
0 routes removed
3895: deleted
Saving tmp/batch_fastest_commute_08_with_14000_routes_of_126839_rows.Rds to tmp
Saving tmp/od_commute_08_with_14000_of_126839_rows.Rds to tmp
2023-02-26 11:21:50 doing batch 09 of 10
Number of rows in batch: 14000
Looking in the file: tmp/batch_fastest_commute_09_with_14000_routes_of_126839_rows.Rds
File does not exist
Starting routing
POSTing the request to create and start the job
Job id: 3896
No data returned yet. Trying again id 3896 every 10 seconds
Congrats, you data is ready
test already exists, overwriting it
Reading in the following file:
C:\Users\earmmor\AppData\Local\Temp\Rtmp6dtZEb/test.csv.gz
Rows: 14000 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): start_id, end_id, strategy, json
dbl (3): distance, time_seconds, calories
/
ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
0 routes removed
3896: deleted
Saving tmp/batch_fastest_commute_09_with_14000_routes_of_126839_rows.Rds to tmp
Saving tmp/od_commute_09_with_14000_of_126839_rows.Rds to tmp
2023-02-26 11:41:51 doing batch 10 of 10
Number of rows in batch: 839
Looking in the file: tmp/batch_fastest_commute_10_with_839_routes_of_126839_rows.Rds
File does not exist
Starting routing
POSTing the request to create and start the job
Job id: 3897
No data returned yet. Trying again id 3897 every 10 seconds
Congrats, you data is ready
test already exists, overwriting it
Reading in the following file:
C:\Users\earmmor\AppData\Local\Temp\Rtmp6dtZEb/test.csv.gz
Rows: 839 Columns: 7
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): start_id, end_id, strategy, json
dbl (3): distance, time_seconds, calories
|
ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
0 routes removed
3897: deleted
Saving tmp/batch_fastest_commute_10_with_839_routes_of_126839_rows.Rds to tmp
Saving tmp/od_commute_10_with_839_of_126839_rows.Rds to tmp
Combining results
✖ error target r_commute
• end pipeline [3.054 hours]
Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Program Files\R\R-4.2.2\library\00LOCK\e1071\libs\x64\e1071.dll to C:\Program Files\R\R-4.2.2\library\e1071\libs\x64\e1071.dll: Permission denied
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Program Files\R\R-4.2.2\library\00LOCK\utf8\libs\x64\utf8.dll to C:\Program Files\R\R-4.2.2\library\utf8\libs\x64\utf8.dll: Permission denied
Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: no applicable method for 'st_as_sf' applied to an object of class "c('dtplyr_step_group', 'dtplyr_step')"

```

**Comment by Robinlovelace** [comment] 2023-02-26 19:39
Are you sure you're running the latest version of the code @mem48 ?

**Comment by Robinlovelace** [comment] 2023-02-26 19:42
This is a good error message in any case: not due to `targets`. The fix is easy: uncomment the `dt` lines of code changed here for a speed-up on scenario estimation: https://github.com/nptscot/npt/commit/db3ca0673762fd88c669b47d8fe31730f2e0b77e

Closing because this is not targets specific. Keep us posted on your progress attempting to reproduce a full build and feel free to re-open if there are any issues you cannot debug.

**Closed by Robinlovelace** 2023-02-26 19:42 UTC
