### ISSUE TITLE
Use new CycleStreets batch API successThreshold parameter

### ISSUE THREAD

**Issue by mvl22** [nptscot/npt#326] opened 2023-11-12 19:39 UTC
See: https://github.com/cyclestreets/cyclestreets-r/issues/86 for a new batch routing API parameter, `successThreshold`, which sets a success threshold for the percentage of routes successfully planned. This is part of work to move away from jobs getting stuck in finalising state.

When implemented in the package, I recommend you set it to lower than 99% for this project. You are sometimes dropping below that because of trying to plan routes too far from known cycle network, e.g. job 6801, so a level of 95% might be better.

**Comment by Robinlovelace** [comment] 2023-11-13 06:25
Partial duplicate of https://github.com/cyclestreets/cyclestreets-r/issues/86 which sets the default to 90.

**Closed by Robinlovelace** 2023-11-13 06:25 UTC

**Comment by mvl22** [comment] 2023-11-13 11:03
Great work. It would be worth documenting though in the code that this is not the same as the published API default. People could assume that 99% will be set without realising it.

You're getting a lower level about 95-98% because I think in this project you are planning an unusually high number of routes in areas with very sparse road networks, such that nearest point resolution is not finding a relevant start/finish point because there is none. Most other clients using it almost always get 100% with only very tiny numbers of failures when OSM has some dodgy data like dead-end one-way streets.

It may be better to set that at a per-project basis here at 90% but have the package use the API default of 99%. I think my suggestion above was rather unclear!
