### ISSUE TITLE
Duplicated desire lines

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#32] opened 2023-02-08 18:27 UTC
In `od_commute_subset` line 3 and 5 are the same.

```
summary(duplicated(od$geometry))
   Mode   FALSE    TRUE 
logical  112522      45 
```

**Comment by Robinlovelace** [comment] 2023-02-09 08:38
Good spot Malcolm. I'm happy to take a look at and fix this.

**Comment by Robinlovelace** [comment] 2023-02-09 08:41
Given that this only applies to 0.04% of the data, less than a 2000th, and given that it will simply mean more flow on the lines that are duplicated, I don't think this is a priority. However will try to diagnose the cause.

**Comment by Robinlovelace** [comment] 2023-02-09 09:30
Confirmed: it's an upstream issue. We could mitigate it on the R side but worth holding out for a fix on the Rust side IMO. Tracking this: https://github.com/dabreegster/odjitter/issues/38

Could be a good first issue if you want to learn Rust Malcolm but suggest that is NOT the best use of time given tight timelines so will add it to the backlog for now.

**Comment by mem48** [comment] 2023-02-09 13:20
I agree not a major issues. But the journey2 function won't accept duplicated requests, so they must be dropped pre routing.

Of course as duplicates they can be added back easily post routeing.

**Comment by Robinlovelace** [comment] 2023-02-09 13:43
Or just add a few lines of code to merge the duplicates, e.g.:

- Identify duplicates (think you've done that)
- Extract the data frames
- Add values in columns with count data, e.g. `bicycle`
- Create new updated desire line with geometry
- Remove the duplicate sf features

Can you give that a bash Malcolm? Should solve our issue for now, unless there are other things to do.

**Comment by Robinlovelace** [comment] 2023-07-14 12:38
Closed in https://github.com/dabreegster/odjitter/issues/38

**Closed by Robinlovelace** 2023-07-14 12:38 UTC
