### ISSUE TITLE
Routing error

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#18] opened 2023-01-26 20:08 UTC
@Robinlovelace FYI

```
NA values detected
NA values detected
NA values detected
NA values detected
NA values detected
NA values detected
NA values detected
NA values detected
\
 *** caught segfault ***
address 0x57e999c90b38, cause 'memory not mapped'
Error in `get_result(output = out, options)`:
! callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
ℹ See `$stderr` for standard error.
Type .Last.error to see the more details.
Session restored from your saved work on 2023-Jan-26 14:26:50 UTC (5 hours ago)
```

**Comment by mem48** [comment] 2023-01-26 20:09
No idea what this means or how to debug on your server

**Comment by Robinlovelace** [comment] 2023-01-26 21:08
No idea either. Restarted.

**Comment by Robinlovelace** [comment] 2023-01-27 12:09
@mem48 seems to be working now, fastest routes completed with following message:

```
Most common output is sf
<simpleError in FUN(ldf[i, 1:2], ldf[i, 3:4], ...): Error: Unrouteable due to one way streets.>
These routes failed: 3889, 3933, 4782, 4874, 4881, 4914, 4915, 5812, 7029, 7040, 7068, 14192, 14292, 14293, 14294, 14295, 14296, 14299, 14300, 14301, 14302, 14303, 14304, 14305, 14306, 14307, 14308, 14309, 14310, 14311, 14312, 14313, 14314, 14315, 14316, 14317, 14318, 14319, 14320, 14321, 14325, 14326, 14336, 14337, 14349, 14350, 14351, 14740, 14741, 14742, 14743, 32868, 32869, 32870, 32871, 32872, 32873, 32874, 32875, 32876, 32877, 32878, 32879, 32880, 32881, 32882, 32883, 32884, 32885, 32886, 32887, 32888, 32889, 32890, 32891, 32892, 32893, 32894, 32895, 32896, 32897, 32898, 32899, 32900, 32901, 32902, 32903, 32904, 32905, 32906, 32907, 32908, 32909, 32910, 32911, 32912, 32913, 32914, 32915, 32916, 32917, 32918, 32919, 32920, 32921, 32922, 32923, 32924, 32925, 32926, 32927, 32928, 32929, 32930, 32931, 32932, 32933, 32934, 32935, 32936, 32937, 32938, 32939, 32940, 32941, 32942, 68190, 68880
The first of which was:
Saving outputdata/routes_max_dist_commute_fastest.Rds
```

Closing for now. Seems to have been a random non-reproducible glitch. Good to report it but also worth a few tries on things like this.

**Closed by Robinlovelace** 2023-01-27 12:09 UTC

**Comment by mem48** [comment] 2023-01-27 12:13
I noticed it had started on the balanced routes. Are you doing the quiet routes and ebike as well?

**Comment by Robinlovelace** [comment] 2023-01-27 13:53
> I noticed it had started on the balanced routes. Are you doing the quiet routes and ebike as well?

See here:

https://github.com/nptscot/npt/blob/eaa5858673112e6114c5dc407fc943e728a866ae/_targets.R#L35

I think we should generate the other routes also. Can you give those a go at some point?

**Comment by mem48** [comment] 2023-01-27 14:17
Are we rate-limited with cyclestreets? If I start sending lots of requests will it interfere with your routing?

**Comment by mem48** [comment] 2023-01-27 14:19
I got rust installed and reproduced the `odjitter` readme

**Comment by Robinlovelace** [comment] 2023-01-27 15:07
> Are we rate-limited with cyclestreets? If I start sending lots of requests will it interfere with your routing?

Not sure but worth asking @mvl22.

**Comment by mem48** [comment] 2023-01-27 15:51
@mvl22 for clarification @Robinlovelace is doing lots of routing using the NPCT API key

![image](https://user-images.githubusercontent.com/15819577/215128784-2f0c48d9-b38e-4f6c-bc3f-9e2af7bf4c7d.png)

The question is if I also start using the key will we cause you any problems

**Comment by Robinlovelace** [comment] 2023-01-27 16:35
Should be done for this round, almost 24 hour job now!

**Comment by mvl22** [comment] 2023-01-27 19:16
Is there some reason you are using the main server and not the dedicated load-balanced endpoint?

**Comment by Robinlovelace** [comment] 2023-01-28 14:46
Another mammoth error. I think this may be targets related. Plan: pull the routing stage out of the pipeline.

Error message below for the record.

<details>

```
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation
*** recursive gc invocation

Traceback:
 1: stats::lag(x, 1)
 2: diff(stats::lag(x, 1))
 3: FUN(X[[i]], ...)
 4: lapply(elev_list, function(x) diff(stats::lag(x, 1)))
 5: json2sf_cs(obj, cols = cols, cols_extra = cols_extra, smooth_gradient,     distance_cutoff, gradient_cutoff, n)
 6: FUN(ldf[i, 1:2], ldf[i, 3:4], ...)
 7: doTryCatch(return(expr), name, parentenv, handler)
 8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 9: tryCatchList(expr, classes, parentenv, handlers)
10: tryCatch({    single_route <- FUN(ldf[i, 1:2], ldf[i, 3:4], ...)    sf::st_sf(cbind(sf::st_drop_geometry(l[rep(i, nrow(single_route)),         ]), route_number = i, sf::st_drop_geometry(single_route)),         geometry = single_route$geometry)}, error = error_fun)
11: route_i(FUN, ldf, wait, i, l, ...)
12: FUN(X[[i]], ...)
13: lapply(X, FUN, ...)
14: pbapply::pblapply(1:nrow(l), function(i) route_i(FUN, ldf, wait,     i, l, ...))
15: route.sf(l = od, route_fun = cyclestreets::journey, plan = plan)
16: stplanr::route(l = od, route_fun = cyclestreets::journey, plan = plan)
17: get_routes(od_commute_subset, plans = plans, purpose = "commute",     folder = "outputdata", batch = FALSE)
18: eval(expr = expr, envir = envir)
19: eval(expr = expr, envir = envir)
20: build_eval_fce17be7(expr, envir)
   code})preserve_seed({    set_seed(list(seed = seed, rng_kind = rng_kind)) 
22: withr::with_seed(seed, build_eval_fce17be7(expr, envir))
23: if_any(anyNA(seed), build_eval_fce17be7(expr, envir), withr::with_seed(seed,     build_eval_fce17be7(expr, envir)))
24: force(code)
25: withr::with_dir(getwd(), if_any(anyNA(seed), build_eval_fce17be7(expr,     envir), withr::with_seed(seed, build_eval_fce17be7(expr,     envir))))
26: build_run_expr(expr, envir, seed, packages, library)
27: withCallingHandlers(build_run_expr(expr, envir, seed, packages,     library), error = capture_error, warning = capture_warning,     tar_condition_cancel = capture_cancel)
28: doTryCatch(return(expr), name, parentenv, handler)
29: tryCatchOne(expr, names, parentenv, handlers[[1L]])
30: tryCatchList(expr, classes, parentenv, handlers)
31: tryCatch(withCallingHandlers(build_run_expr(expr, envir, seed,     packages, library), error = capture_error, warning = capture_warning,     tar_condition_cancel = capture_cancel), error = function(condition) {})
32: build_init(expr = command$expr, envir = envir, seed = command$seed,     packages = command$packages, library = command$library)
33: command_produce_build(target$command, envir)
34: builder_update_build(target, frames_get_envir(frames))
35: target_run.tar_builder(target = target, envir = self$envir, path_store = self$meta$get_path_store())
36: target_run(target = target, envir = self$envir, path_store = self$meta$get_path_store())
37: self$run_target(name)
38: if_any(target_should_run(target, self$meta), self$run_target(name),     self$skip_target(target))
39: self$process_target(self$scheduler$queue$dequeue())
40: self$process_next()
41: local_init(pipeline = pipeline, meta = meta_init(path_store = path_store),     names = names, shortcut = shortcut, queue = queue, reporter = reporter,     envir = tar_option_get("envir"))$run()
ne))    queue <- if_any(pipeline_uses_priorities(pipeline), "parallel",         "sequential")    local_init(pipeline = pipeline, meta = meta_init(path_store = path_store),         names = names, shortcut = shortcut, queue = queue, reporter = reporter,         envir = tar_option_get("envir"))$run()    invisible()})(path_store = "_targets", names_quosure = ~NULL, shortcut = FALSE,     reporter = "verbose", pipeline = <environment>)
43: do.call(targets_function, targets_arguments)
44: targets::tar_callr_inner_try(targets_function = targets_function,     targets_arguments = targets_arguments, options = options,     envir = envir, parent = parent, script = script, store = store,     fun = fun)
45: doTryCatch(return(expr), name, parentenv, handler)
46: tryCatchOne(expr, names, parentenv, handlers[[1L]])
47: tryCatchList(expr, classes, parentenv, handlers)
    fun = fun), error = function(condition) condition)tion = targets_function,     targets_arguments = targets_arguments, options = options,     envir = envir, parent = parent, script = script, store = store, 
49: (function (targets_function, targets_arguments, options, envir = NULL,     script, store, fun) {    force(envir)    parent <- parent.frame()    tryCatch(targets::tar_callr_inner_try(targets_function = targets_function,         targets_arguments = targets_arguments, options = options,         envir = envir, parent = parent, script = script, store = store,         fun = fun), error = function(condition) condition)})(targets_function = base::quote(function (pipeline, path_store,     names_quosure, shortcut, reporter) {    pipeline_reset_deployments(pipeline)    names <- tar_tidyselect_eval(names_quosure, pipeline_get_names(pipeline))    queue <- if_any(pipeline_uses_priorities(pipeline), "parallel",         "sequential")    local_init(pipeline = pipeline, meta = meta_init(path_store = path_store),         names = names, shortcut = shortcut, queue = queue, reporter = reporter,         envir = tar_option_get("envir"))$run()    invisible()}), targets_arguments = base::quote(list(path_store = "_targets",     names_quosure = ~NULL, shortcut = FALSE, reporter = "verbose")),     options = base::quote(list(crayon.enabled = TRUE)), script = base::quote("_targets.R"),     store = base::quote("_targets"), fun = base::quote("tar_make"))
function (pipeline, path_store,     names_quosure, shortcut, reporter) {    pipeline_reset_deployments(pipeline)    names <- tar_tidyselect_eval(names_quosure, pipeline_get_names(pipeline))    queue <- if_any(pipeline_uses_priorities(pipeline), "parallel",         "sequential")    local_init(pipeline = pipeline, meta = meta_init(path_store = path_store),         names = names, shortcut = shortcut, queue = queue, reporter = reporter,         envir = tar_option_get("envir"))$run()    invisible()}, targets_arguments = list(path_store = "_targets", names_quosure = ~NULL,     shortcut = FALSE, reporter = "verbose"), options = list(crayon.enabled = TRUE),     script = "_targets.R", store = "_targets", fun = "tar_make")),     envir = base::quote(<environment>), quote = base::quote(TRUE))
51: do.call(do.call, c(readRDS("/tmp/Rtmp7VlUs0/callr-fun-5b5774625205c"),     list(envir = .GlobalEnv, quote = TRUE)), envir = .GlobalEnv,     quote = TRUE)
52: saveRDS(do.call(do.call, c(readRDS("/tmp/Rtmp7VlUs0/callr-fun-5b5774625205c"),     list(envir = .GlobalEnv, quote = TRUE)), envir = .GlobalEnv,     quote = TRUE), file = "/tmp/Rtmp7VlUs0/callr-res-5b5774ea2dde9",     compress = FALSE)
rror("error in callr subprocess")        class(e2) <- c("callr_remote_error", class(e2))        e2 <- err$add_trace_back(e2)        cut <- which(e2$trace$scope == "global")[1]        if (!is.na(cut)) {            e2$trace <- e2$trace[-(1:cut), ]        }        saveRDS(list("error", e2, e), file = paste0("/tmp/Rtmp7VlUs0/callr-res-5b5774ea2dde9",             ".error"))    }}, interrupt = function(e) {    {        callr_data <- as.environment("tools:callr")$`__callr_data__`        err <- callr_data$err        if (FALSE) {            assign(".Traceback", .traceback(4), envir = callr_data)            dump.frames("__callr_dump__")            assign(".Last.dump", .GlobalEnv$`__callr_dump__`,                 envir = callr_data)            rm("__callr_dump__", envir = .GlobalEnv)        }        e <- err$process_call(e)        e2 <- err$new_error("error in callr subprocess")        class(e2) <- c("callr_remote_error", class(e2))        e2 <- err$add_trace_back(e2)        cut <- which(e2$trace$scope == "global")[1]        if (!is.na(cut)) {            e2$trace <- e2$trace[-(1:cut), ]        }        saveRDS(list("error", e2, e), file = paste0("/tmp/Rtmp7VlUs0/callr-res-5b5774ea2dde9",             ".error"))    }}, callr_message = function(e) {    try(signalCondition(e))})
54: doTryCatch(return(expr), name, parentenv, handler)
55: tryCatchOne(expr, names, parentenv, handlers[[1L]])
56: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
57: doTryCatch(return(expr), name, parentenv, handler)
58: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
59: tryCatchList(expr, classes, parentenv, handlers)
h(stderr())    NULL    invisible()}, error = function(e) {    {        callr_data <- as.environment("tools:callr")$`__callr_data__`        err <- callr_data$err        if (FALSE) {            assign(".Traceback", .traceback(4), envir = callr_data)            dump.frames("__callr_dump__")            assign(".Last.dump", .GlobalEnv$`__callr_dump__`,                 envir = callr_data)            rm("__callr_dump__", envir = .GlobalEnv)        }        e <- err$process_call(e)        e2 <- err$new_error("error in callr subprocess")        class(e2) <- c("callr_remote_error", class(e2))        e2 <- err$add_trace_back(e2)        cut <- which(e2$trace$scope == "global")[1]        if (!is.na(cut)) {            e2$trace <- e2$trace[-(1:cut), ]        }        saveRDS(list("error", e2, e), file = paste0("/tmp/Rtmp7VlUs0/callr-res-5b5774ea2dde9",             ".error"))    }}, interrupt = function(e) {    {        callr_data <- as.environment("tools:callr")$`__callr_data__`        err <- callr_data$err        if (FALSE) {            assign(".Traceback", .traceback(4), envir = callr_data)            dump.frames("__callr_dump__")            assign(".Last.dump", .GlobalEnv$`__callr_dump__`,                 envir = callr_data)            rm("__callr_dump__", envir = .GlobalEnv)        }        e <- err$process_call(e)        e2 <- err$new_error("error in callr subprocess")        class(e2) <- c("callr_remote_error", class(e2))        e2 <- err$add_trace_back(e2)        cut <- which(e2$trace$scope == "global")[1]        if (!is.na(cut)) {            e2$trace <- e2$trace[-(1:cut), ]        }        saveRDS(list("error", e2, e), file = paste0("/tmp/Rtmp7VlUs0/callr-res-5b5774ea2dde9",             ".error"))    }}, callr_message = function(e) {    try(signalCondition(e))}), error = function(e) {    NULL    if (FALSE) {        try(stop(e))    }    else {        invisible()    }}, interrupt = function(e) {    NULL    if (FALSE) {        e    }    else {        invisible()    }})
ecoverable exception occurred. R is aborting now ...
Error in `get_result(output = out, options)`:
! callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
ℹ See `$stderr` for standard error.
Type .Last.error to see the more details.
Session restored from your saved work on 2023-Jan-28 05:25:24 UTC (9 hours ago)
```

</details>

More info soon.

**Comment by Robinlovelace** [comment] 2023-01-28 14:51
Routing underway.

```
> # tar_make_clustermq() configuration (okay to leave alone):
> options(clustermq.scheduler = "multicore")
> # Run the R scripts in the R/ folder with your custom functions:
> tar_source()
> plans = c("fastest", "balanced")
> plans = c("fastest", "balanced")
> min_flow = 1 # Set to 1 for full build, set to high value (e.g. 400) for tests
> tar_load(od_commute_subset)
> r_commute = get_routes(od_commute_subset, plans = plans, purpose = "commute",
+                            folder = "outputdata", batch = FALSE)
Getting the fastest routes for commute journeys
Getting the fastest routes
Routes already exist: reading from file
Getting the balanced routes for commute journeys
Getting the balanced routes
  |                                                  | 0 % ~calculating 
```

**Comment by mvl22** [comment] 2023-01-30 10:09
Sounds like you’ve resolved whatever the problem was. A route issue at our end presumably shouldn’t be causing R to crash so I guess there was some bug at your end?

PS Can you confirm you’re using the dedicated Leeds endpoint?
