### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by mem48** [nptscot/npt#313] opened 2023-10-27 10:30 UTC
```
✖ error target rs_commute_fastest
▶ end pipeline [2.56 minutes]
Warning messages:
1: package 'sf' was built under R version 4.2.3 
2: package 'future' was built under R version 4.2.3 
3: package 'future.callr' was built under R version 4.2.3 
Error:
! Error running targets::tar_make_future()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: Timeout was reached: [api.cyclestreets.net] Operation timed out after 60006 milliseconds with 0 bytes received
```

The schools routing completed but commute routing keeps failing

**Comment by Robinlovelace** [comment] 2023-10-27 10:33
Have you tried updating `cyclestreets` @mem48 ?

**Comment by Robinlovelace** [comment] 2023-10-27 10:33
See https://github.com/cyclestreets/cyclestreets-r/commit/cc94cfbe15f15ac00635cabf4222b3845ea91ede

**Comment by Robinlovelace** [comment] 2023-10-27 10:34
We can increase than number but in my experience 600 seconds (10 minutes or 600000 miliseconds) should be fine.

**Comment by mem48** [comment] 2023-10-27 10:35
Trying update now. The jobs were sent to cyclestreets succesfully.

**Comment by Robinlovelace** [comment] 2023-10-27 10:35
Can you run the second line here and report back? I see why you added `FALSE` above this line Malcolm but suspect it's the cause of this issue:

https://github.com/nptscot/npt/blob/c07aec33ebd530a72919073015a3b3dddd2a2bf9/_targets.R#L11C11-L11C18

**Comment by Robinlovelace** [comment] 2023-10-27 10:36
https://github.com/nptscot/npt/blob/c07aec33ebd530a72919073015a3b3dddd2a2bf9/_targets.R#L11C11-L11C18

**Comment by Robinlovelace** [comment] 2023-10-27 10:36
Sounds like it's fixed. Closing for now. Hopefully it works, it's a lot of data to upload!

**Closed by Robinlovelace** 2023-10-27 10:36 UTC
